#!/bin/sh
echo "================================="
echo "NODE: Running asset pipeline"
echo "================================="
node ./generateAssets.js --scss_in=../_assets/scss/**/*.scss --scss_out=../_site/assets/css
node ./generateAssets.js --js_in=../_assets/js/**/*.js --js_out=../_site/assets/js
node ./generateAssets.js --img_in=../_assets/img/**/* --img_out=../_site/assets/img

node ./generateCollectionStubs.js --clean --jekyll_src=../ --list_in=../_site/assets/data/category_listing.csv --type=categories
node ./generateCollectionStubs.js --clean --jekyll_src=../ --list_in=../_site/assets/data/tag_listing.csv --type=tags
