#!/bin/sh
echo "================================="
echo "NODE: Running asset pipeline"
echo "================================="
node ./asset_pipeline.js --scss_in=../_assets/scss/**/*.scss --scss_out=../_site/assets/css
node ./asset_pipeline.js --js_in=../_assets/js/**/*.js --js_out=../_site/assets/js
node ./asset_pipeline.js --img_in=../_assets/img/**/* --img_out=../_site/assets/img
